theme: jekyll-theme-minimal
title: Julio César Echeverri Marulanda
description: Desarrolador de software, con experiencia en desarrollo web y móvil. Apasionado por la tecnología y la innovación.
# logo: /assets/img/profile.png
